runtime: nodejs18

env_variables:
  MODEL_URL: "https://storage.googleapis.com/halodek-project/ML/js/model_f/model.json"
  
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.7

handlers:
  - url: /.*
    script: auto

